//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiseUygulamasi.DAT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AtBahisEntities : DbContext
    {
        public AtBahisEntities()
            : base("name=AtBahisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AtBilgisi> AtBilgisi { get; set; }
        public virtual DbSet<BahisTipleri> BahisTipleri { get; set; }
        public virtual DbSet<Hipodrom> Hipodrom { get; set; }
        public virtual DbSet<Sonuc> Sonuc { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Bulten> Bulten { get; set; }
        public virtual DbSet<Kupon> Kupon { get; set; }
    }
}
