//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtYarisi_OzgurBIKMAZ.DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sonuc
    {
        public int SonucID { get; set; }
        public int HipodromID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public int KosuID { get; set; }
        public int AtID { get; set; }
        public int Siralama { get; set; }
        public int atNo { get; set; }
    
        public virtual AtBilgisi AtBilgisi { get; set; }
    }
}
